### ISSUE TITLE
Prendre en compte la boîte englobante du calque osm

### ISSUE THREAD

**Issue by npalix** [jecor/bati-fusion#1]
Le calque OSM peut ne contenir qu'une partie de la commune (car il n'est pas toujours possible de télécharger toute la commune d'un coup avec la XAPI). Dans ce cas, il est nécessaire d'exclure les bâtiments du cadastre qui sont en dehors de la boîte englobante du calque OSM.

**Comment by jecor** [comment]
Disponible dans la version 0.2.
