### ISSUE TITLE
Les versions linux et windows donnent des résultats différents

### ISSUE THREAD

**Issue by JVillafruela** [jecor/bati-fusion#3]
A l'occasion de l'[atelier du groupe local grenoblois](https://wiki.openstreetmap.org/wiki/Grenoble_groupe_local/Agenda#lundi_15_novembre_2021_Atelier_outils_de_mise_.C3.A0_jour_du_b.C3.A2ti) consacré aux outils d'intégration du cadastre j'ai refait des essais et j'ai constaté un comportement étrange : les versions linux et windows ne donnent pas les mêmes résultats pour les mêmes données en entrée. La version Linux me semble donner les bons résultats.

J'ai recompilé les sources avec : 

- linux : gcc (Debian 10.2.1-6) 10.2.1 20210110
- windows : gcc.exe (Rev2, Built by MSYS2 project) 11.2.0

J'avais modifié le Makefile pour produire un binaire statique (`LDFLAGS = -static`) 

J'ai testé différentes communes : 

|Commune|Statut
|---|---|
|Bressieux|OK|
|Cognet|KO|
|Poisat|KO|
|Sinard|KO|
|Villard-Bonnot|KO|

Les fichiers sont disponibles pendant quelque temps : http://cadastre.openstreetmap.fr/data/038/

J'ai utilisé à chaque fois le fichier XXX-houses.osm du cadastre et j'ai obtenu le bâti dans OSM par la requête : 

```
[out:json][timeout:25];
{{geocodeArea:Cognet}}->.searchArea;
(
  // query part for: “building=*”
  node["building"](area.searchArea);
  way["building"](area.searchArea);
  relation["building"](area.searchArea);
);
out body;
>;
out skel qt;
```

Je joins les fichiers pour Cognet (petite commune)

`bati-fusion GL116-COGNET-houses.osm cognet-buildings-osm.osm out`

```
tail log*
==> log-linux.txt <==
 - current ID 224517586, recouvrement: 99.38%
 - current ID 224517624, recouvrement: 6.31%
Enregistrement fichiers de sortie...
=======================================
Way OK:          4
Way sans fusion: 3
Way fusionnees:  37
Way en conflit:  60
Way exclus:      2
=======================================

==> log-win.txt <==
Chargement de cognet-buildings-osm.osm...
Fusion...
Enregistrement fichiers de sortie...
=======================================
Way OK:          0
Way sans fusion: 0
Way fusionnees:  0
Way en conflit:  0
Way exclus:      106
=======================================
```

Avec le fichier contenant toutes les données OSM de la commune le résultat windows est encore différent : 

```
bati-fusion.exe GL116-COGNET-houses.osm cognet-all-osm.osm all
Chargement de GL116-COGNET-houses.osm...
Chargement de cognet-all-osm.osm...
Fusion...
Enregistrement fichiers de sortie...
=======================================
Way OK:          106
Way sans fusion: 0
Way fusionnees:  0
Way en conflit:  0
Way exclus:      0
=======================================
```

[Cognet.zip](https://github.com/jecor/bati-fusion/files/7564078/Cognet.zip)

**Comment by jecor** [comment]
Bonjour Jérôme,

désolé pour le retard de cette réponse. Je n'ai malheureusement pas accès à un ordinateur Windows ici tout de suite (avec compilateur qui plus est).

J'aurais deux requêtes pour compléter tes fichiers de Cognet (je te confirme que sous macOS, j'ai bien le même résultat que sous Linux):

- Peux-tu m'envoyer les deux fichiers de log linux et windows pour tes exécutions sur les fichiers de Cognet? Cela aiderait grandement à comparer pour moi.
- Autre chose: je vois que tu as l'air d'utiliser la "vieille" version 0.2 (et mea culpa cela semble être la dernière version targuée). Peux-tu aussi faire un essai avec la version de développement disponible sur master? Celle-ci améliore grandement les sorties (mais peut présenter le même bug).

**Comment by JVillafruela** [comment]
Bonjour Jérôme,

J'ai recompilé à partir des sources (e79c278) et ça a résolu le problème (voir logs joints)  :-) 

J'ai aussi réessayé sur une commune plus étendue (Sinard) et là aussi les deux versions donnent le même résultat.

Merci d'avoir pris le temps de regarder le problème.

[log-linux.txt](https://github.com/jecor/bati-fusion/files/7656593/log-linux.txt)
[log-win.txt](https://github.com/jecor/bati-fusion/files/7656594/log-win.txt)
